### ISSUE TITLE
Get pub/sub working

### ISSUE THREAD

**Issue by jackieokay** [ros2/rmw_freertps#1]
Features that need to be implemented for this to happen:
- [x] message typesupport and serialization
- [ ] rmw_create_publisher, rmw_destroy_publisher
  - [ ] rmw_publish
- [ ] rmw_create_subscriber, rmw_destroy_subscriber
- [ ] rmw_wait
- [ ] rmw_create_guard_condition, rmw_destroy_guard_condition (possibly optional, but helpful)
  - [ ] rmw_trigger_guard_condition (optional)

**Comment by clalancette** [comment]
Closing this out to archive the repository.
